kind: Service
apiVersion: v1
metadata:
  name: ngx-rocket-service
spec:
  selector:
    app: ngx-rocket
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngx-rocket-deploy
  labels:
    app: ngx-rocket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngx-rocket
  template:
    metadata:
      labels:
        app: ngx-rocket
    spec:
      containers:
      - name: ngx-rocket
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
